version: "3.7"

services:
  database:
    image: "postgres:alpine3.18"
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

  node:
    container_name: remix
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3001:3000
    entrypoint: ./start.sh